//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub mod prelude;

pub mod channel;
pub mod class;
pub mod file;
pub mod invite;
pub mod membership;
pub mod message;
pub mod report;
pub mod sea_orm_active_enums;
pub mod user;
