//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::channel::Entity as Channel;
pub use super::class::Entity as Class;
pub use super::file::Entity as File;
pub use super::invite::Entity as Invite;
pub use super::membership::Entity as Membership;
pub use super::message::Entity as Message;
pub use super::report::Entity as Report;
pub use super::user::Entity as User;
