//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_type")]
pub enum UserType {
    #[sea_orm(string_value = "Admin")]
    Admin,
    #[sea_orm(string_value = "Mod")]
    Mod,
    #[sea_orm(string_value = "Regular")]
    Regular,
}
